### ISSUE TITLE
The question about the teachers' checkpoint

### ISSUE THREAD

**Issue by WangzcBruce** [Adamdad/KnowledgeFactor#2]
Excuse me, are these ckpts pretrained by ImageNet? I trained the wideresnet's teacher model with a pretrained ckpt solely on cifar10 initially and found it started at a accuracy of 50%, so I guess the ckpts aren't pretrained on the datasets of cifar10/100. Is that right?

**Comment by Adamdad** [comment]
Dear WangzcBruce, May I know which exact pretrained weights you are using? I only provide the teacher weights on CIFAR10 with WideResNet28-2 and 28-10. If those are enough for your own experiments, you can actually train the teacher on your data sets. And make sure your are loading it correctly with `mmcls`, since `mmcls` wrap the network architecture with a `classifier` object.
