### ISSUE TITLE
Some equation errors in the paper

### ISSUE THREAD

**Issue by zxhr2793** [Adamdad/KnowledgeFactor#3]
Nice work and the code. I find some equation errors in the main text.
1. The upper bound of I(X,T_j) should be E_{p(x)}D_{KL} not the E_{p(t_j)}D_{KL} in Equ.(7) and Equ.(19) in supplementary materials.
2. The D_{KL} in Equ.(11) misses a minus before 1/2. But your released code is correct.

**Comment by Adamdad** [comment]
Wow, Thank you so much for the proofreading of the formulation. 
1. You are correct that the expectation should be over $x$ rather than $t_j$, as derived below. I'll update the arxiv version as soon as possible.
![image](https://user-images.githubusercontent.com/26020510/189695036-313e909b-21e0-4d72-a477-05b94a4d65d9.png)

2. You are right there should be a minus symbol over 11.

Thank you again for your suggestion !!!!!!!! Great !!!!!
